spring:
  datasource:
    url: jdbc:postgresql://localhost:4321/postgres
    username: postgres
    password: pass
  jpa:
    databasePlatform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update